config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'

 controller :sessions do
   get 'login' => :new
   post 'login' => :create
   delete 'logout' => :destroy
 end

   scope '(:locale)' do 
      resources :users
      resources :orders
      resources :line_items
      resources :carts
      resources :products do
        get :who_bought, :on => :member
      end
      root :to => 'store#index', :as => 'store'
   end
end

  
  

  

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  
  def total_price
    product.price * quantity
  end
  
  # an easy way to remember where to put belongs_to declarations: if a table has foreign keys, the corresponding model should have a belongs_to for each.
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_filter :authorize, :only => :create
  
  # GET /line_items
  # GET /line_items.xml
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.xml
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.xml
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.xml
  def create
    @cart =  current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
    # LineItem.new(params[:line_item]) 

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to(store_url)}
        format.js { @current_item = @line_item}
        format.xml  { render :xml => @line_item, 
          :status => :created, :location => @line_item }
      else
        format.html { render :action => "new"}
        format.xml  { render :xml => @line_item.errors, 
          :status => :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.xml
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to(@line_item, :notice => 'Line item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @line_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.xml
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to(line_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %> 
	<td><%= line_item.quantity %>&times;</td> 
	<td><%= line_item.product.title %></td> 
	<td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
			line_item.quantity,
			truncate(line_item.product.title, :length => 50)) %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>